- name: Commit playlist
  run: |
    git config --global user.name "github-actions[bot]"
    git config --global user.email "github-actions@github.com"
    git add playlist.m3u
    git commit -m "update playlist" || echo "no change"
    git pull --rebase
    git push
